export const CATEGORIES = {
  'Meat & Poultry':    ['Chicken','Beef','Pork','Lamb','Turkey','Duck'],
  'Fish & Seafood':    ['Salmon','Tuna','Shrimp','White Fish','Shellfish'],
  'Vegetarian':        ['Pasta','Rice & Grains','Salads','Soups','Stir Fry'],
  'Vegan':             ['Legumes','Tofu & Tempeh','Raw','Smoothies'],
  'Breakfast':         ['Eggs','Pancakes & Waffles','Oats','Smoothie Bowls'],
  'Baking & Pastries': ['Bread','Cakes','Cookies','Pastries','Pies'],
  'Desserts':          ['Ice Cream','Puddings','Chocolate','Fruit Desserts'],
  'Drinks':            ['Coffee','Tea','Cocktails','Juices','Smoothies'],
  'Sides & Salads':    ['Salads','Roasted Veg','Dips & Sauces'],
  'Cuisine':           ['Italian','Asian','Mexican','Middle Eastern','Indian'],
};

export const MAIN_CATEGORY_NAMES = Object.keys(CATEGORIES);

const MAIN_TAG_CLASS = {
  'Meat & Poultry':    'tag-meat',
  'Fish & Seafood':    'tag-seafood',
  'Vegetarian':        'tag-veg',
  'Vegan':             'tag-vegan',
  'Breakfast':         'tag-breakfast',
  'Baking & Pastries': 'tag-baking',
  'Desserts':          'tag-desserts',
  'Drinks':            'tag-drinks',
  'Sides & Salads':    'tag-sides',
  'Cuisine':           'tag-cuisine',
};

// Legacy map for recipes created before the category rework
const LEGACY_TAG_CLASS = {
  'Pastries':    'tag-baking',
  'Baking':      'tag-baking',
  'Breakfast':   'tag-breakfast',
  'Desserts':    'tag-desserts',
  'Drinks':      'tag-drinks',
  'Main Course': 'tag-meat',
  'Meats':       'tag-meat',
  'Pasta':       'tag-veg',
  'Salads':      'tag-sides',
  'Seafood':     'tag-seafood',
  'Vegetarian':  'tag-veg',
  'Soups':       'tag-veg',
  'Snacks':      'tag-sides',
  'Side Dishes': 'tag-sides',
  'Appetizers':  'tag-sides',
};

export const tagClass = (mainCat) =>
  MAIN_TAG_CLASS[mainCat] || LEGACY_TAG_CLASS[mainCat] || 'tag-other';

export const formatCreator = (name, isAI) =>
  isAI ? `AI generated by ${name}` : `By ${name}`;

export function isTableMissing(err) {
  return (
    err.code === '42P01' || err.code === 'PGRST200' ||
    (err.message && (err.message.includes('does not exist') || err.message.includes('schema cache')))
  );
}

export function normalizeIng(raw) {
  let s = raw.toLowerCase().trim();
  for (let pass = 0; pass < 3; pass++) {
    s = s
      .replace(/^[\d\s½¼¾⅓⅔⅛⅜⅝⅞.,/×x+\-]+/, '')
      .replace(/^(a|an)\s+/, '')
      .replace(/^(cups?|tbsps?|tsps?|tablespoons?|teaspoons?|grams?|kg|oz|ounces?|ml|liters?|lbs?|pounds?|cloves?|pinch|handful|bunch|large|medium|small|cans?|packages?|packets?|slices?|pieces?|strips?|sprigs?|dashes?|drops?)\s+(of\s+)?/i, '')
      .trim();
  }
  return s
    .replace(/\s*\([^)]*\)/g, '')
    .replace(/,\s*(optional|to taste|room temperature|softened|diced|chopped|minced|sliced|grated|shredded|crumbled|peeled|fresh|dried|frozen|cooked|uncooked|cooled|melted|beaten|sifted|divided|roughly|finely).*$/i, '')
    .replace(/,.*$/, '')
    .trim();
}
