export const CATEGORIES = {
  'Meat & Poultry':    ['Chicken','Beef','Pork','Lamb','Turkey','Duck'],
  'Fish & Seafood':    ['Salmon','Tuna','Shrimp','White Fish','Shellfish'],
  'Vegetarian':        ['Pasta','Rice & Grains','Salads','Soups','Stir Fry'],
  'Vegan':             ['Legumes','Tofu & Tempeh','Raw','Smoothies'],
  'Breakfast':         ['Eggs','Pancakes & Waffles','Oats','Smoothie Bowls'],
  'Baking & Pastries': ['Bread','Cakes','Cookies','Pastries','Pies'],
  'Desserts':          ['Ice Cream','Puddings','Chocolate','Fruit Desserts'],
  'Drinks':            ['Coffee','Tea','Cocktails','Juices','Smoothies'],
  'Sides & Salads':    ['Salads','Roasted Veg','Dips & Sauces'],
  'Cuisine':           ['Italian','Asian','Mexican','Middle Eastern','Indian'],
};

export const MAIN_CATEGORY_NAMES = Object.keys(CATEGORIES);

const MAIN_TAG_CLASS = {
  'Meat & Poultry':    'tag-meat',
  'Fish & Seafood':    'tag-seafood',
  'Vegetarian':        'tag-veg',
  'Vegan':             'tag-vegan',
  'Breakfast':         'tag-breakfast',
  'Baking & Pastries': 'tag-baking',
  'Desserts':          'tag-desserts',
  'Drinks':            'tag-drinks',
  'Sides & Salads':    'tag-sides',
  'Cuisine':           'tag-cuisine',
};

// Legacy map for recipes created before the category rework
const LEGACY_TAG_CLASS = {
  'Pastries':    'tag-baking',
  'Baking':      'tag-baking',
  'Breakfast':   'tag-breakfast',
  'Desserts':    'tag-desserts',
  'Drinks':      'tag-drinks',
  'Main Course': 'tag-meat',
  'Meats':       'tag-meat',
  'Pasta':       'tag-veg',
  'Salads':      'tag-sides',
  'Seafood':     'tag-seafood',
  'Vegetarian':  'tag-veg',
  'Soups':       'tag-veg',
  'Snacks':      'tag-sides',
  'Side Dishes': 'tag-sides',
  'Appetizers':  'tag-sides',
};

export const tagClass = (mainCat) =>
  MAIN_TAG_CLASS[mainCat] || LEGACY_TAG_CLASS[mainCat] || 'tag-other';

export const formatCreator = (name, isAI) =>
  isAI ? `AI generated by ${name}` : `By ${name}`;

export function isTableMissing(err) {
  return (
    err.code === '42P01' || err.code === 'PGRST200' ||
    (err.message && (err.message.includes('does not exist') || err.message.includes('schema cache')))
  );
}

export function normalizeIng(raw) {
  // Replace unicode fractions first
  let s = raw.replace(/[½¼¾⅓⅔⅛⅜⅝⅞]/g, m =>
    ({ '½':'1/2','¼':'1/4','¾':'3/4','⅓':'1/3','⅔':'2/3','⅛':'1/8','⅜':'3/8','⅝':'5/8','⅞':'7/8' }[m] ?? m)
  ).toLowerCase().trim();

  const UNIT = '(?:cups?|tbsps?|tbs|teaspoons?|tsps?|tablespoons?|fluid\\s+oz|fl\\.?\\s*oz\\.?|grams?|kg|mg|oz\\.?|ounces?|ml|milliliters?|liters?|litres?|lbs?\\.?|pounds?|dl|cl|cloves?|pinch(?:es)?|handful(?:s)?|bunch(?:es)?|head(?:s)?|large|medium|small|cans?|packages?|pkgs?|packets?|slices?|pieces?|strips?|sprigs?|stalks?|dashes?|drops?|g(?=\\s|$))';

  for (let pass = 0; pass < 3; pass++) {
    s = s
      // strip leading mixed number, fraction, or decimal (e.g. "1 1/2", "3/4", "2.5", "2-3")
      .replace(/^\d+\s+\d+\/\d+/, '')
      .replace(/^\d+\/\d+(\s+to\s+\d+\/?\d*)?/, '')
      .replace(/^\d+(\.\d+)?(\s*[-–]\s*\d+(\.\d+)?)?/, '')
      .trim()
      // strip attached metric abbreviation left after number strip (e.g. "ml", "g", "kg")
      .replace(/^(ml|g|kg|mg|dl|cl)(?=\s|$)/i, '')
      .trim()
      // strip leading unit word
      .replace(new RegExp(`^${UNIT}\\b\\.?\\s*(?:of\\s+)?`, 'i'), '')
      .replace(/^(a|an|some)\s+/, '')
      .trim();
  }

  return s
    .replace(/\s*\([^)]*\)/g, '')
    .replace(/^(dried|fresh|frozen|whole|raw|ground|powdered|crushed|canned|bottled|cooked|toasted|roasted)\s+/i, '')
    .replace(/,\s*(optional|to taste|room temperature|softened|diced|chopped|minced|sliced|grated|shredded|crumbled|peeled|fresh|dried|frozen|cooked|uncooked|cooled|melted|beaten|sifted|divided|roughly|finely|thinly|very\s+thinly).*$/i, '')
    .replace(/,.*$/, '')
    .trim();
}
